### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mdgrossi** [MattGrossi-NOAA/mattgrossi-noaa.github.io#1]
The following errors need correction:
- **About** / Longer version
  - [x] "importatnly" ➡️ "importantly"
- **Research**
  - [x] "...interests are diverse include..." add "and"
  - [x] Landing page: "*R/V* Hugh R. Sharp" ➡️  "R/V *Hugh R. Sharp*"
  - [x] NPQ page: "*R/V* Hugh R. Sharp" ➡️  "R/V *Hugh R. Sharp*" (two places)
  - [x] NPQ page: '"...coastal ocean",' ➡️ '"...coastal ocean,"'
  - [x] RTOFS page: "*R/V* Gulf Stream Eagle" ➡️ "R/V *Gulf Stream Eagle*"
- **Talks**
  - [x] "Underwater Gliders User Group Workshop (UG2)" ➡️ "Underwater Gliders User Group (UG2) Workshop"

**Comment by MattGrossi-NOAA** [comment]
All fixed in 5948b7e.
